# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.3
  - nightly

before_script:
  - git config --global user.name "GitUser"
  - git config --global user.email "git@us.er"

addons:
  apt:
    packages:
      - cmake
      - xorg-dev
      - mesa-utils

codecov: true
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Observables"); Pkg.test("Observables"; coverage=true)'
matrix:
  allow_failures:
    - julia: nightly
    - julia: 1.0
  fast_finish: true
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
notifications:
  email: false
