Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.5
os:
  - linux
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  allow_failures:
    - julia: 1.5
  include:
  - stage: "Documentation"
    julia: 1.5
    os: linux
    env:
      ssh: ${{ secrets.DOCUMENTER_KEY }}
    script:
      - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                             Pkg.instantiate()'
      - julia --project=docs/ docs/make.jl
    after_success: skip
